version: '3.9'

services:
  postgres:
    # image: postgres:14-alpine
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=burgher


      # psql -h <hostname> -p 5432 -U user -d <database>
      # psql postgresql://user:password@localhost:5432/burgher